### ISSUE TITLE
Westend faucet returning error "ECONNREFUSED 127.0.0.1:5555"

### ISSUE THREAD

**Issue by laboon** [paritytech/substrate-matrix-faucet#127]
Whenever anyone requests WND from the Westend Faucet ( https://riot.w3f.tech/#/room/#westend_faucet:matrix.org ) , they get the error:

connect ECONNREFUSED 127.0.0.1:5555

However, it looks like the WND actually do get sent.

**Comment by PierreBesson** [comment]
The faucets have failed their upgrades:
```
[2022-04-08T10:09:08.724] [INFO] default - Starting faucet v1.1.2
[2022-04-08T10:09:08.727] [INFO] default - Faucet backend listening on port 5555.
/backend/node_modules/@polkadot/util/assert.cjs:37
    throw new Error((0, _function.isFunction)(message) ? message() : message);
          ^

Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
    at assert (/backend/node_modules/@polkadot/util/assert.cjs:37:11)
    at /backend/node_modules/@polkadot/util-crypto/node_modules/@polkadot/wasm-crypto/bridge.cjs:36:22
    at sr25519PairFromSeed (/backend/node_modules/@polkadot/util-crypto/sr25519/pair/fromSeed.cjs:24:82)
    at Object.sr25519 (/backend/node_modules/@polkadot/keyring/keyring.cjs:24:56)
    at Keyring.createFromUri (/backend/node_modules/@polkadot/keyring/keyring.cjs:271:115)
    at Keyring.addFromUri (/backend/node_modules/@polkadot/keyring/keyring.cjs:188:30)
    at Keyring.addFromMnemonic (/backend/node_modules/@polkadot/keyring/keyring.cjs:148:17)
    at /backend/build/src/server/actions.js:44:40
```

I think https://github.com/paritytech/substrate-matrix-faucet/commit/111fd74936169c4641f263b3be871febbc9e84af broke them. Ping @sergejparity

**Comment by PierreBesson** [comment]
It looks like there is currently a duplicate deployment of the faucet, one correctly running and sending funds, the other being the broken one sending `error "ECONNREFUSED 127.0.0.1:5555"`.

```
kubectl get po
NAME                              READY   STATUS             RESTARTS   AGE
rococo-faucet-6654f6cd89-g5n2n    1/2     Error              291        25h
rococo-faucet-68d4d589df-zm5nv    2/2     Running            0          13d
westend-faucet-66b549dc9b-4qlr6   1/2     CrashLoopBackOff   290        25h
westend-faucet-c48c996bd-lsb4r    2/2     Running            0          13d
```

The Kubernetes Deployment should probably use a ["recreate strategy" ](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) rather than `RollingUpdate` to prevent having two active faucets at any one time.

**Comment by sergejparity** [comment]
Yes. This should not be related to change I've made yesterday. I only hardcoded path to Vault secret. Without it next pipeline run would fail as `$CI_PROJECT_PATH` has changed from `parity/substrate-matrix-faucet` to `parity/mirrors/substrate-matrix-faucet` as project was moved.

**Comment by lovelaced** [comment]
A double deploy has never happened before this as far as I know, @sergejparity could you add the recreate strategy and try running the pipeline again?

**Comment by sergejparity** [comment]
@lovelaced @PierreBesson can you take a look at https://github.com/paritytech/substrate-matrix-faucet/pull/128 whether it is the right way to do so?

**Comment by PierreBesson** [comment]
Okay so the recreate strategy is now in place, however the problem is that the current code refuses to start and output the logs from https://github.com/paritytech/substrate-matrix-faucet/issues/127#issuecomment-1092705145
