### ISSUE TITLE
Health should return server error HTTP status 512 (made up) when at least an error happened either on the bot or the server

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate-matrix-faucet#17]
The current `/health` is dead simple https://github.com/paritytech/substrate-matrix-faucet/blob/main/src/server/index.ts#L18-L20

If the server crashed, it'll return something else (404 or 500 I guess). But the server should not crash any more since any error is now handled. Also worth noting, the `/bot` is a separate service, if it crashes there's nothing telling us.

Talking with @fevo1971 the other day, and based on https://github.com/paritytech/substrate-matrix-faucet/issues/6#issuecomment-729248180, it'd be good to return something else than 200 if some errors have happened, (like #3 or #2, still open and that will likely happen in the future). Similarly, the `bot` should ping the `server` when it crashed, to give us a heads-up. You can then couple this health check with whatever tool you have (prometheus?).

I'm thinking about a super simple error counter, whenever an error is caught, we increase it. `/health` will answer 512 (the first [HTTP status server](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) error that isn't a standard) and we should check `server` and `bot` logs for errors. I'd add some info in the 512 response body eventually with how many errors on which side, low cost and can help.

Depending on how this works, and how much it spams, we can enhance it.

I'd implement that next depending on what you think @fevo1971 @lovelaced

**Comment by lovelaced** [comment]
I think an error counter would be absolutely great actually. Honestly then we don't necessarily need a /health we just need a /metrics with a single prometheus-style counter metric for errors and can alert on that. /health could be reserved for something more basic. Behavior looks something like this:

```
$ curl http://localhost:3000/metrics 
# HELP my_metric_identifier an example counter metric
# TYPE my_metric_identifier counter my_metric_identifier 3
```
