### ISSUE TITLE
Perform yarn install and build at build time instead of runtime

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/substrate-matrix-faucet#189]
In the [Dockerfile at line 22](https://github.com/paritytech/substrate-matrix-faucet/blob/main/bot_injected.Dockerfile#L22), we can see that the dependency downloading and typescript builds are done at runtime. This is contrary to best practices (executable not immutable) and is the reason for a somewhat slow start.

**Comment by mutantcornholio** [comment]
It's in the `RUN` command, which is build-time.

**Comment by PierreBesson** [comment]
You are correct. I think I confused this with another issue. Thanks for correcting me.
