### ISSUE TITLE
Add E2E tests to all endpoints

### ISSUE THREAD

**Issue by Bullrich** [paritytech/substrate-matrix-faucet#212]
This includes:
- `/drip`
- `/drip/bot`
- `/drip/web`

**Comment by Bullrich** [comment]
Hey @mordamax & @rzadp I just realized I don't really know if this can be achieved.

We need a valid captcha which can not be obtained without some kind of UI automation.

There is some tools to do [automated testing](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do) but I think that's intended for UI testing, not API testing.

**Comment by rzadp** [comment]
In https://github.com/paritytech/substrate-matrix-faucet/pull/219 I have an E2E test which calls the `drip/web` endpoint, and the backend uses a testing captcha secret which makes any captcha token valid.

Maybe it will be enough for an E2E smoke test.

**Comment by Bullrich** [comment]
> In #219 I have an E2E test which calls the `drip/web` endpoint, and the backend uses a testing captcha secret which makes any captcha token valid.
> 
> Maybe it will be enough for an E2E smoke test.

Oh amazing. Will use that knowledge then. Thank you!

**Comment by mordamax** [comment]
the api also has programmatic way to get a token, so may be that could be alternative option with "special" testing keys
https://web.archive.org/web/20230127150134/https://developers.google.com/recaptcha/docs/invisible

```js
grecaptcha.execute('key', {action: 'homepage'}).then((token) => {
               ...
});
```
