### ISSUE TITLE
Update Grafana dashboard, alerts, etc after argoCD migration

### ISSUE THREAD

**Issue by rzadp** [paritytech/substrate-matrix-faucet#228]
After https://github.com/paritytech/substrate-matrix-faucet/pull/226, we need to update Grafana dashboards and alerts.

- [ ] [Grafana dashboard](https://grafana.parity-mgmt.parity.io/d/1_Am4RJ4z/faucets?orgId=1&refresh=5m)
- [x] Links https://gitlab.parity.io/groups/parity/opstooling/-/wikis/home
- [ ] [(manual) ink! balance alert ](https://grafana.parity-mgmt.parity.io/alerting/grafana/CZRHdC14z/view?returnTo=%2Falerting%2Flist)
- [ ] (automated in terraform) balance alerts (?)

**Comment by rzadp** [comment]
Hey @PierreBesson, shall we collaborate on this?

I'd like to fix the dashboard but I'm not seeing any metrics in Thanos and I don't know if there is anything I can do on my end.

Also wanted to double check that `loki.parity-versi` is the correct source of the Versi faucet logs?

**Comment by PierreBesson** [comment]
@rzadp Please discuss internal Parity deployments on internal issue trackers and reserve this one for the faucet development.
