### ISSUE TITLE
Race condition (?) when loading Recaptcha in the web faucet

### ISSUE THREAD

**Issue by rzadp** [paritytech/substrate-matrix-faucet#242]
Seems like there is a race condition when loading Recaptcha.

It appears when opening the faucet in Firefox.

To reproduce:

1. Start the app

```
cd client
export PUBLIC_FAUCET_URL="https://example.com/test"      
export PUBLIC_CAPTCHA_KEY="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
npm run build && npm run preview 
```

2. Open the site in Firefox

3. Reload the page without cache a couple of times.

Sometimes, the captcha does not load.
Sometimes without any error, sometimes with `TypeError: window.grecaptcha.render is not a function`

cc @Bullrich

**Comment by Bullrich** [comment]
@rzadp good job on finding this issue!

It was as you mentioned, a race condition.

I created #243 to fix this issue, so now the methods will wait to be instantiated and then the captcha script will be imported.
