### ISSUE TITLE
Feature request: add web3.foundation matrix accounts to list of privileged users

### ISSUE THREAD

**Issue by lovelaced** [paritytech/substrate-matrix-faucet#72]
As title. Currently this is limited to matrix.parity.io accounts.

**Comment by AndreiEres** [comment]
But how it looks?
Exactly `@bill:web3.foundation`?

**Comment by lovelaced** [comment]
> But how it looks?
> Exactly `@bill:web3.foundation`?

Yes, exactly.

**Comment by chevdor** [comment]
I am in this code, I can add that
